language: ruby
rvm:
- 2.4.0
before_install:
- export | grep SAUCE_
env:
  global:
  - SAUCE_USERNAME=sauce_examples
addons:
  jwt:
    secure: kEwjrHum3aL1RNQSXz/jrZksgcmHT1DeHvhEA4KNYz8C+WpHo6Ba2/GTTIMR0ayyz97X+kD4aOQ1xiXkyalF8RH9RysWj/zPHJqGImFnd+iH5LfxDjPX4mCO9RFfgJLTucFrGuqTqQ7V0OQ8OwmMEFRf66a4cJSIonhz+2P88RQvlwfE0Qw3hOE8ErC6pqM6Vbq2QRCImaqXCTJ0bwkLGT9TV96PvbyUZwiV7lz5TMyZNFEZ9bmRphZFiEmFkKB31I0IOnJImoIvFEBY60TLXNsZatVCrtRk3bmbELBY2J1zehheByHrwmfTclV6BO5BAdv3knUSbpiy0P7jLeQdZdOTj14HPadFAv/R8Ac9QU+S98k0SwitlGrSxo1MCptIqA/cCX449oQt5NX85OeLylIoC2kj52SlMFtp7kGlsoliNr/GRvFTTO78MGlWg/PhaMAupVtQznMr/g4L9lSi/5J4u4NuGc9D5uwIrUo7qnIBLNfpceePY/rO0/Fd6RbNYyzBl5gL1BctnB/tABJSCJboHSLL8gX/Hh97xN0/SOTcV91Ny6O6/keYX331bR0xrWRxYR63PhrYvyW3ldFoT0r53Jst4YuSUmNRghjHDnteMjdiZGQyPyvKPAQNs90ZkaeZK2DomGP0Lucm8C110fregy5WsPCO89bp8hK+Wyo=
